<?php

/**
 * Implementation of hook_features_api().
 */
function wysiwyg_features_api() {
  return array(
    'wysiwyg' => array(
      'name' => t('Wysiwyg profiles'),
      'default_hook' => 'wysiwyg_default_profiles',
      'default_file' => FEATURES_DEFAULTS_INCLUDED,
      'feature_source' => TRUE
    ),
  );
}

/**
 * Implementation of hook_features_export_options().
 */
function wysiwyg_features_export_options() {
  return _features_wysiwyg_profiles_list();
}

/**
 * Implementation of hook_features_export().
 */
function wysiwyg_features_export($data, &$export, $module_name = '') {
  // The wysiwyg_default_formats() hook integration is provided by the
  // features module so we need to add it as a dependency.
  $export['dependencies']['wysiwyg'] = 'wysiwyg';
  $export['dependencies']['fe_wysiwyg'] = 'fe_wysiwyg';

  foreach ($data as $name) {
    if ($profile = _features_wysiwyg_profile_load($name)) {
      // Add profile to exports
      $export['features']['wysiwyg'][$profile->format] = $profile->format;

      // The editor module is included as a dependency
      $export['dependencies'][$profile->editor] = $profile->editor;
    }
  }

  $pipe = array();
  return $pipe;
}

/**
 * Implementation of hook_features_export_render().
 */
function wysiwyg_features_export_render($module, $data, $export = NULL) {
  $code = array();
  $code[] = '  $profiles = array();';
  $code[] = '';

  foreach ($data as $name) {
    if ($profile = _features_wysiwyg_profile_load($name)) {
      $profile_export = features_var_export($profile, '  ');
      $profile_identifier = features_var_export($profile->format);
      $code[] = "  // Exported profile: {$profile->format}";
      $code[] = "  \$profiles[{$profile_identifier}] = {$profile_export};";
      $code[] = "";
    }
  }

  $code[] = '  return $profiles;';
  $code = implode("\n", $code);
  return array('wysiwyg_default_profiles' => $code);
}

/**
 * Implementation of hook_features_revert().
 */
function wysiwyg_features_revert($module) {
  return wysiwyg_features_rebuild($module);
}

/**
 * Implementation of hook_features_rebuild().
 */
function wysiwyg_features_rebuild($module) {
  if ($defaults = features_get_default('wysiwyg', $module)) {
    foreach ($defaults as $profile) {
      db_merge('wysiwyg')
        ->key(array('format' => $profile['format']))
        ->fields(array(
          'editor' => $profile['editor'],
          'settings' => serialize($profile['settings']),
        ))
        ->execute();

      wysiwyg_profile_cache_clear();
    }
  }
}

/**
 * Load a wysiwyg format by its name.
 */
function _features_wysiwyg_profile_load($name) {
  return wysiwyg_get_profile($name);
}

/**
 * Load a wysiwyg format by its name.
 */
function _features_wysiwyg_profiles_list () {
  $profiles = wysiwyg_profile_load_all();
  $names = array_keys($profiles);
  return array_combine($names, $names);
}
